version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  api:
    build: .
    command: rails -p 8080 -b '0.0.0.0'
    volumes:
      - .:/ciderchain_api
    ports:
      - "8080:8080"
    depends_on:
      - db
